Implement Scale Encode and Decode Traits for Light Client
polytope-labs/sync-committee-rs pull request #20
Opened 2023-03-18 08:44 UTC by dharjeezy

Implements Derived types for easy scale codec encoding and decoding

2023-03-20 07:21 UTC, Wizdave97 requested changes
We also need the reverse case from our derived types to the ethreum consensus types.

2023-03-20 09:43 UTC, Wizdave97 commented on primitives/src/derived_types.rs
> +			parent_root: beacon_block_header.parent_root.as_bytes().try_into().unwrap(),
Use `expect` instead of `unwrap()`

2023-03-20 09:45 UTC, Wizdave97 requested changes

2023-03-20 09:45 UTC, Wizdave97 commented on primitives/src/derived_types.rs
> +			parent_root: beacon_block_header.parent_root.as_bytes().try_into().unwrap(),
Or better still let's implement `TryFrom`  instead of `From`

2023-03-20 09:45 UTC, Wizdave97 commented
With `TryFrom` we can just return errors when conversion fails.

2023-03-20 16:39 UTC, dharjeezy commented
> @dharjeezy This is still not implemented
> 
> > We also need the reverse case from our derived types to the ethereum consensus types.

Yes, i am on it.

2023-03-21 09:22 UTC, Wizdave97 approved these changes

2023-03-21 10:24 UTC, merged