CI on merge
polytope-labs/sync-committee-rs pull request #23
Opened 2023-03-25 14:15 UTC by iTranscend

run ci only on merge to main

2023-03-25 14:35 UTC, seunlanlege requested changes

2023-03-25 14:35 UTC, seunlanlege commented on .github/workflows/test.yml
> -  pull_request:
Check workflow should still run on pull request, only test should run on merge

2023-03-25 16:13 UTC, seunlanlege approved these changes

2023-03-27 07:49 UTC, Wizdave97 commented
@iTranscend  add a gpg key to your github account and local git so your commits can be signed.
https://docs.github.com/en/enterprise-server@3.5/authentication/managing-commit-signature-verification/adding-a-gpg-key-to-your-github-account

2023-03-27 07:50 UTC, merged